### ISSUE TITLE
Kernel crash when attempting to access /proc

### ISSUE THREAD

**Issue by dwalkes** [olivierpierre/flashmon#1]
Thanks for sharing this project!

I've noticed i see a segfault attempting to cat out the /proc files.

The fix in [my local branch](https://github.com/Trellis-Logic/flashmon/tree/fix_segfault) resolved the issue for me, see [this commit](https://github.com/Trellis-Logic/flashmon/commit/97dc0eca08c3d3de31eb4614578b0146103698d5)

Let me know if you'd like me to prepare a pull request.

**Comment by olivierpierre** [comment]
Hi Dan,

Thanks a lot for the correction! Indeed I wrote that code while I was still
a student, not aware of copy_to_user! Yes, if you can do a pull request
I'll merge it right away.

Thanks again!

Pierre

**Comment by dwalkes** [comment]
Sure thing Pierre, I've submitted a pull request.

**Comment by olivierpierre** [comment]
Thanks Dan
Pierre
